// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUZwyiH3NNE7LC_hjgW28FYH7fW3CWYI',
    appId: '1:223169796281:web:1786e2ad118f7addd2e368',
    messagingSenderId: '223169796281',
    projectId: 'stopwatch-project-3b1f7',
    authDomain: 'stopwatch-project-3b1f7.firebaseapp.com',
    storageBucket: 'stopwatch-project-3b1f7.appspot.com',
    measurementId: 'G-VFXT04SPNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMfPXc1BG5AdwaWrsnUrMOqL1wrH2Guds',
    appId: '1:223169796281:android:10ce61ea5ee1ab38d2e368',
    messagingSenderId: '223169796281',
    projectId: 'stopwatch-project-3b1f7',
    storageBucket: 'stopwatch-project-3b1f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbu-iO-DyGpv5pTbAahsvJkgn4r1uc87s',
    appId: '1:223169796281:ios:3c4de950ef19bf18d2e368',
    messagingSenderId: '223169796281',
    projectId: 'stopwatch-project-3b1f7',
    storageBucket: 'stopwatch-project-3b1f7.appspot.com',
    iosBundleId: 'com.example.countus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbu-iO-DyGpv5pTbAahsvJkgn4r1uc87s',
    appId: '1:223169796281:ios:3c4de950ef19bf18d2e368',
    messagingSenderId: '223169796281',
    projectId: 'stopwatch-project-3b1f7',
    storageBucket: 'stopwatch-project-3b1f7.appspot.com',
    iosBundleId: 'com.example.countus',
  );
}
